### ISSUE TITLE
Unknown Error?

### ISSUE THREAD

**Issue by SteadyStatus21** [concierge/discord#2]
Concierge-bot> /kpm install discord
Attempting to install module from "https://github.com/concierge/discord.git"...
An unknown error occurred while installing "discord".
Concierge-bot>
It fails, and does nothing...

Can you help me please?

Thanks,
SteadyStatus21

**Comment by drkno** [comment]
Haven't looked at this since 2017, so there is a good chance it doesn't work at all.
However, it would be helpful to start it with [debug log level](https://github.com/concierge/Concierge/blob/master/doc/Options.md) to know what the actual error was.
